### ISSUE TITLE
'Reset Settings' initially sets colors to black and not their default values

### ISSUE THREAD

**Issue by TimCreasman** [openbible-io/openbible#1]
**Environment**
Chromium v114.0.5735.198

---

**Reproduction steps:**
* Navigate to the 'Settings' page.
* Without changing any settings click the 'Reset Settings' button.
* The colors update to black (#000000)
<img width="429" alt="Screenshot 2023-06-29 at 3 58 37 PM" src="https://github.com/openbible-io/openbible/assets/8962809/b24e57e5-6662-4021-8607-8e39d3405e8e">

* This warning is also logged to the console:
<img width="507" alt="Screenshot 2023-06-29 at 4 23 20 PM" src="https://github.com/openbible-io/openbible/assets/8962809/9b9a1874-112f-4d1d-b123-3e54a50f8a75">

---

**Expected Behavior**
The colors should reset to their original gray/blue colors.

---

**Notes**
* If you hit the 'Reset Settings' button again, the css resets to the correct colors.
* The bugged black css does not actually get applied even if the settings are saved.

**Comment by thesmartwon** [comment]
Fixed in 08a82b23206cf7c41335749b6fa91b56af6a6362
