### ISSUE TITLE
All reader panels can be removed, soft-locking the user

### ISSUE THREAD

**Issue by TimCreasman** [openbible-io/openbible#2]
**Environment**
Chromium v114.0.5735.198

---

**Reproduction steps:**
* While on the reader page, click the 'x' button to remove the reader panel.
* Repeat this until the page is blank.
* With no way to add a new reader, the user is soft-locked with a blank screen. Refreshing does not resolve the issue.
<img width="592" alt="Screenshot 2023-06-29 at 4 19 14 PM" src="https://github.com/openbible-io/openbible/assets/8962809/a157375e-2391-4721-a022-560d986c9173">

---

**Notes**
* You can get out of the soft lock state by deleting localstorage and refreshing.

**Comment by thesmartwon** [comment]
Fixed in f6520a7ac8523c6147fb8487a26523bdf836802f
